output_folder: "/home/storage/capture/"
camera:
  # 0:
  #   name: "526摄像机_装车南料位西"
  #   rtsp_url: "rtsp://admin:blt12345@10.226.13.40:554/h264/ch1/main/av_stream"
  #   video_length: 30  # 单位秒
  # 1:
  #   name: "526工控机"
  #   rtsp_url: "rtsp://10.226.13.244:8554/desktop"
  #   video_length: 40  # 单位秒
  0:
    name: "751_备用工控机"
    rtsp_url: "rtsp://10.226.13.219:8554/desktop"
    video_length: 40  # 单位秒
  1:
    name: "751摄像机_装车南料位东"
    rtsp_url: "rtsp://admin:blt12345@10.226.13.14:554/h264/ch1/main/av_stream"
    video_length: 30  # 单位秒
docker:
  0:
    hosts: "10.226.13.24"
    container_name: "cli"
    log_lines: 2000 # 单位行
  1:
    hosts: "10.226.13.24"
    container_name: "ser"
    log_lines: 2000 # 单位行


