output_folder: r"D:\开源项目\capture"

camera_0:
  name: "526摄像机_装车南料位西"
  rtsp_url: "rtsp://admin:blt12345@10.226.13.40:554/h264/ch1/main/av_stream"
  video_length: 60  # 单位秒
docker:
  log_lines: 2000
  container_name: "cli"

